# Usa l'immagine ufficiale di Eclipse Mosquitto
FROM eclipse-mosquitto

# Copia il file di configurazione locale nel container
COPY mosquitto.conf /mosquitto/config/mosquitto.conf

# Espone la porta di Mosquitto
EXPOSE 1883
